apiVersion: v1
kind: Service
metadata:
  name: analytics-nodeport-svc
spec:
  type: NodePort
  selector:
    app: analytics
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008 # Strictly bound to port 30008 per specs