FROM hshar/webapp:latest
# Copy all cloned repository website files into Apache webroot
COPY . /var/www/html/
EXPOSE 80
CMD ["apache2ctl", "-D", "FOREGROUND"]
~                                                                                                                                                                                                                  
~                                         